name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Test
        run: go test -v ./...

  build:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./builds/namaztime ./cmd/main.go